var NumberOfWords = 116

var words = new BuildArray(NumberOfWords)

// Use the following variables to 
// define your random words:
words[1] = "Micimackó"
words[2] = "Kőolaj"
words[3] = "Benzingőz"
words[4] = "Gyerekzár"
words[5] = "Rokkantkocsi"
words[6] = "Ruháskosár"
words[7] = "Bundáskenyér"
words[8] = "Bakkecske"
words[9] = "Gyapjúszőnyeg"
words[10] = "Babaágy"
words[11] = "Selyemhernyó"
words[12] = "Számlatömb"
words[13] = "Almafa"
words[14] = "Bordélyház"
words[15] = "Tükörtojás"
words[16] = "Elemlámpa"
words[17] = "Pásztorkutya"
words[18] = "Tüzifa"
words[19] = "Ködlámpa"
words[20] = "Faág"
words[21] = "Éjjeliszekrény"
words[22] = "Széndioxid"
words[23] = "Gondolatolvasás"
words[24] = "Kenyérpirító"
words[25] = "Családfa"
words[26] = "Kutatócsoport"
words[27] = "Szervkereskedelem"
words[28] = "Rakottkrumpli"
words[29] = "Befőttesüveg"
words[30] = "Villámcsapás"
words[31] = "Agydaganat"
words[32] = "Tűznyelő"
words[33] = "Fagyáspont"
words[34] = "Aranyeső"
words[35] = "Gumilabda"
words[36] = "Nadrágszíj"
words[37] = "Gyerekjáték"
words[38] = "Madártej"
words[39] = "Borospince"
words[40] = "Tőkehal"
words[41] = "Dobverő"
words[42] = "Bélcsavarodás"
words[43] = "Fűszál"
words[44] = "Télapó"
words[45] = "Visszajátszás"
words[46] = "Közellenség"
words[47] = "Lemezlovas"
words[48] = "Országház"
words[49] = "Szolgasors"
words[50] = "Ütvefúró"
words[51] = "Szorítókötés"
words[52] = "Önkritika"
words[53] = "Repülőtér"
words[54] = "Költőpénz"
words[54] = "Tojástartó"
words[55] = "Távcső"
words[56] = "Családtag"
words[57] = "Öregasszony"
words[58] = "Alagút"
words[59] = "Jelszó"
words[60] = "Szivargyújtó"
words[61] = "Varródoboz"
words[62] = "Boroshordó"
words[63] = "Tejszínhab"
words[64] = "Mestermű"
words[65] = "Bukósisak"
words[66] = "Csavarhúzó"
words[67] = "Durrdefekt"
words[68] = "Egyirányú utca"
words[69] = "Gyalogátkelőhely"
words[70] = "Lakat"
words[71] = "Láncolaj"
words[72] = "Láthatósági mellény"
words[73] = "Macskaszem"
words[74] = "Pótgumi"
words[75] = "Sebességváltó"
words[76] = "Széldzseki"
words[77] = "Jobbkézszabály"
words[78] = "Kerékpártároló"
words[79] = "Kilométeróra"
words[80] = "Körforgalom"
words[81] = "Kulcstartó"
words[82] = "Szelepsapka"
words[83] = "Tricikli"
words[84] = "Bohóc"
words[85] = "Állatkert"
words[86] = "Bakancslista"
words[87] = "Bajuszfésű"
words[88] = "Bárányhimlő"
words[89] = "Dobostorta"
words[90] = "Dohánylevél"
words[91] = "Húsgombóc"
words[92] = "Gitárhúr"
words[93] = "Göncölszekér"
words[94] = "Világháború"
words[95] = "Hangverseny"
words[96] = "Mellimplantátum"
words[97] = "Injekcióstű"
words[98] = "Kávébab"
words[99] = "Cserépkályha"
words[100] = "Katasztrófafilm"
words[101] = "Kígyóméreg"
words[102] = "Konzervnyitó"
words[103] = "Korcsolyapálya"
words[104] = "Kürtőskalács"
words[105] = "Elakadásjelző hárömszög"
words[106] = "Botmixer"
words[107] = "Mogyoróhéj"
words[108] = "Napraforgó"
words[109] = "Pingpongasztal"
words[110] = "Rongybaba"
words[111] = "Hétfejű sárkány"
words[112] = "Sípcsont"
words[113] = "Sóbánya"
words[114] = "Tábortűz"
words[115] = "Ugrálóvár"
words[116] = "Vámpírfog"

function BuildArray(size){
this.length = size
for (var i = 1; i <= size; i++){
this[i] = null}
return this
}

function PickRandomWord(mfr) {
// Generate a random number between 1 and NumberOfWords
var rnd = Math.ceil(Math.random() * NumberOfWords)

// Display the word inside the text box
mfr.WordBox.value = words[rnd]
}